/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AppDesktopPenjualanPC;

import javax.swing.JOptionPane;

/**
 *
 * @author ALFIAN
 */
public class Project extends javax.swing.JFrame {
Spek objek = new Spek();
    /**
     * Creates new form Project
     */
    public Project() {
        initComponents();
        nonaktif();
    }
    
    void bersih(){
    tNama.setText("");
    tEmail.setText("");
    cPaket.setSelectedIndex(0);
    tSpek.setText("");
    tHarga.setText("");
    tAlamat.setText("");
    r1.setSelected(false);
    r2.setSelected(false);
    r3.setSelected(false);
    tKeterangan.setText("");
    tBiaya.setText("");
    cMetode.setSelectedIndex(0);
    tTotal.setText("");
    }
    
    void aktif(){
    tNama.requestFocus();
    tNama.setEnabled(true);
    tEmail.setEnabled(true);
    tSpek.setEnabled(true);
    tHarga.setEnabled(true);
    tAlamat.setEnabled(true);
    tKeterangan.setEnabled(true);
    tBiaya.setEnabled(true);
    tTotal.setEnabled(true);
    }
    
    void nonaktif(){
    tNama.setEnabled(false);
    tEmail.setEnabled(false);
    tSpek.setEnabled(false);
    tHarga.setEnabled(false);
    tAlamat.setEnabled(false);
    tKeterangan.setEnabled(false);
    tBiaya.setEnabled(false);
    tTotal.setEnabled(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        r1 = new javax.swing.JRadioButton();
        r3 = new javax.swing.JRadioButton();
        r2 = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        tSpek = new javax.swing.JTextField();
        tNama = new javax.swing.JTextField();
        tEmail = new javax.swing.JTextField();
        cPaket = new javax.swing.JComboBox<>();
        tHarga = new javax.swing.JTextField();
        tKeterangan = new javax.swing.JTextField();
        tBiaya = new javax.swing.JTextField();
        tTotal = new javax.swing.JTextField();
        cMetode = new javax.swing.JComboBox<>();
        bIsi = new javax.swing.JButton();
        bPesan = new javax.swing.JButton();
        bTutup = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        tAlamat = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\ALFIAN\\Downloads\\AA1.jpg")); // NOI18N
        jLabel2.setMinimumSize(new java.awt.Dimension(27, 18));
        jLabel2.setPreferredSize(new java.awt.Dimension(27, 18));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setForeground(new java.awt.Color(51, 51, 0));
        jPanel1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        jLabel6.setText("QR-COMP");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, -1, -1));

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jLabel17.setText("JUAL & BELI ONLINE KOMPUTER/PC GAMING");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 460, 90));

        jPanel3.setBackground(new java.awt.Color(51, 0, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\ALFIAN\\Downloads\\AA2.jpg")); // NOI18N
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 190, 250, 170));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\ALFIAN\\Downloads\\AA1.jpg")); // NOI18N
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 220, 150));

        jLabel1.setFont(new java.awt.Font("Cooper Black", 0, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ALFIAN\\Downloads\\AAA1.png")); // NOI18N
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, -20, 310, 150));

        jLabel19.setIcon(new javax.swing.ImageIcon("C:\\Users\\ALFIAN\\Downloads\\AAA2.jpg")); // NOI18N
        jPanel4.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 90, -1, -1));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 210, 510));

        jLabel20.setFont(new java.awt.Font("Stencil", 0, 23)); // NOI18N
        jLabel20.setText("PICTURE");
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 100, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 250, 610));

        jLabel4.setText("jLabel4");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 570, -1, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel7.setText("NAMA PEMESAN");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel8.setText("E-MAIL");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 250, 30));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel9.setText("PAKET PC");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel10.setText("SPESIFIKASI");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel11.setText("HARGA PC");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel12.setText("JASA PENGIRIMAN");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, -1));

        r1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        r1.setText("JNE");
        r1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r1ActionPerformed(evt);
            }
        });
        jPanel1.add(r1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, -1, -1));

        r3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        r3.setText("GO-SEND");
        r3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r3ActionPerformed(evt);
            }
        });
        jPanel1.add(r3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 380, -1, -1));

        r2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        r2.setText("J&T EXPRESS");
        r2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r2ActionPerformed(evt);
            }
        });
        jPanel1.add(r2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 380, -1, -1));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel13.setText("BIAYA PENGIRIMAN");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, -1, -1));

        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel15.setText("TOTAL BAYAR");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 560, -1, -1));

        jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel16.setText("KETERANGAN");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, -1, -1));

        jLabel18.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel18.setText("METODE PEMBAYARAN");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, -1, -1));

        tSpek.setBackground(new java.awt.Color(240, 240, 240));
        tSpek.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        tSpek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tSpekActionPerformed(evt);
            }
        });
        jPanel1.add(tSpek, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 210, 30));

        tNama.setBackground(new java.awt.Color(240, 240, 240));
        tNama.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jPanel1.add(tNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 210, 30));

        tEmail.setBackground(new java.awt.Color(240, 240, 240));
        tEmail.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        tEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tEmailActionPerformed(evt);
            }
        });
        jPanel1.add(tEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 210, 30));

        cPaket.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        cPaket.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-PILIH-", "SUPER", "EXTRA", "PREMIUM", "HIGH", "LOW" }));
        cPaket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cPaketActionPerformed(evt);
            }
        });
        jPanel1.add(cPaket, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 90, 30));

        tHarga.setEditable(false);
        tHarga.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jPanel1.add(tHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 130, 30));

        tKeterangan.setBackground(new java.awt.Color(240, 240, 240));
        tKeterangan.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jPanel1.add(tKeterangan, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 430, 210, 30));

        tBiaya.setEditable(false);
        tBiaya.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        tBiaya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tBiayaActionPerformed(evt);
            }
        });
        tBiaya.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tBiayaKeyPressed(evt);
            }
        });
        jPanel1.add(tBiaya, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 470, 130, 30));

        tTotal.setEditable(false);
        tTotal.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        tTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tTotalActionPerformed(evt);
            }
        });
        jPanel1.add(tTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 550, 130, 30));

        cMetode.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        cMetode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-PILIH-", "BCA", "BRI", "BNI", "MANDIRI", "INDOMARET", "ALFAMART" }));
        cMetode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cMetodeActionPerformed(evt);
            }
        });
        jPanel1.add(cMetode, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 510, -1, 30));

        bIsi.setBackground(new java.awt.Color(102, 102, 102));
        bIsi.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bIsi.setText("ISI DATA");
        bIsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bIsiActionPerformed(evt);
            }
        });
        jPanel1.add(bIsi, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 470, 90, 30));

        bPesan.setBackground(new java.awt.Color(0, 51, 0));
        bPesan.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bPesan.setText("PESAN");
        bPesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPesanActionPerformed(evt);
            }
        });
        jPanel1.add(bPesan, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 530, 90, 30));

        bTutup.setBackground(new java.awt.Color(153, 0, 0));
        bTutup.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bTutup.setText("TUTUP");
        bTutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTutupActionPerformed(evt);
            }
        });
        jPanel1.add(bTutup, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 560, 90, 30));

        jLabel21.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel21.setText("ALAMAT LENGKAP");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, -1));

        tAlamat.setBackground(new java.awt.Color(240, 240, 240));
        jPanel1.add(tAlamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 210, 30));

        jButton1.setBackground(new java.awt.Color(102, 102, 102));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("BERSIH");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 500, 90, 30));

        jPanel5.setBackground(new java.awt.Color(102, 0, 0));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 600, 450, 10));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void r3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r3ActionPerformed
       r1.setSelected(false);
       r2.setSelected(false);
       objek.setJasa(r3.getText());
       objek.pilih2(objek.getJasa());
       tKeterangan.setText(objek.getKeterangan());
       tBiaya.setText(Integer.toString(objek.getBiaya()));
    }//GEN-LAST:event_r3ActionPerformed

    private void r1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r1ActionPerformed
       r2.setSelected(false);
       r3.setSelected(false);
       objek.setJasa(r1.getText());
       objek.pilih2(objek.getJasa());
       tKeterangan.setText(objek.getKeterangan());
       tBiaya.setText(Integer.toString(objek.getBiaya()));
    }//GEN-LAST:event_r1ActionPerformed

    private void tSpekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tSpekActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tSpekActionPerformed

    private void tEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tEmailActionPerformed

    private void cPaketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cPaketActionPerformed
       objek.setPaket(cPaket.getSelectedItem().toString());
       objek.pilih1(objek.getPaket());
       tSpek.setText(objek.getSpesifikasi()); 
       tHarga.setText(Integer.toString(objek.getHarga()));
       tSpek.requestFocus();
    }//GEN-LAST:event_cPaketActionPerformed

    private void r2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r2ActionPerformed
       r1.setSelected(false);
       r3.setSelected(false);
       objek.setJasa(r2.getText());
       objek.pilih2(objek.getJasa());
       tKeterangan.setText(objek.getKeterangan());
       tBiaya.setText(Integer.toString(objek.getBiaya()));
    }//GEN-LAST:event_r2ActionPerformed

    private void tTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tTotalActionPerformed
      
    }//GEN-LAST:event_tTotalActionPerformed

    private void tBiayaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tBiayaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tBiayaActionPerformed

    private void tBiayaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tBiayaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tBiayaKeyPressed

    private void cMetodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cMetodeActionPerformed
       objek.setMetode(cMetode.getSelectedItem().toString());
       objek.pilih3(objek.getMetode()); 
       tTotal.setText(Integer.toString(objek.getTotal())); 
    }//GEN-LAST:event_cMetodeActionPerformed

    private void bIsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bIsiActionPerformed
        aktif();
    }//GEN-LAST:event_bIsiActionPerformed

    private void bPesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPesanActionPerformed
       JOptionPane.showMessageDialog(null, "Kode Pembayaran Anda : "+objek.getKode());
       JOptionPane.showMessageDialog(null, "Pesanan Akan Di Proses Bila Pembayaran Sudah Masuk", "Pemesanan Anda Behasil !!", JOptionPane.INFORMATION_MESSAGE);
       bersih();
    }//GEN-LAST:event_bPesanActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       bersih();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void bTutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTutupActionPerformed

        int tutup;
        tutup=JOptionPane.showConfirmDialog(null, "Yakin Tutup Program?" ,"Konfirmasi",JOptionPane.YES_NO_OPTION);
        if(tutup==JOptionPane.YES_OPTION)
            dispose();
        else
            return;
    }//GEN-LAST:event_bTutupActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Project.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Project.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Project.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Project.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Project().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bIsi;
    private javax.swing.JButton bPesan;
    private javax.swing.JButton bTutup;
    private javax.swing.JComboBox<String> cMetode;
    private javax.swing.JComboBox<String> cPaket;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton r1;
    private javax.swing.JRadioButton r2;
    private javax.swing.JRadioButton r3;
    private javax.swing.JTextField tAlamat;
    private javax.swing.JTextField tBiaya;
    private javax.swing.JTextField tEmail;
    private javax.swing.JTextField tHarga;
    private javax.swing.JTextField tKeterangan;
    private javax.swing.JTextField tNama;
    private javax.swing.JTextField tSpek;
    private javax.swing.JTextField tTotal;
    // End of variables declaration//GEN-END:variables
}
