/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AppDekstopHotel;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author DANDY RIANSYAH


*/
public class PemesananHotel extends javax.swing.JFrame {
    Alamat almt = new Alamat();  
    Integer harga;
    /**
     * Creates new form PemesananHotel
     */
     public PemesananHotel() {
        initComponents();
        nonaktif();
    }

      
        
        void bersih(){
        c1.setSelected(false);
        c2.setSelected(false);
        c3.setSelected(false);
        tHarga.setText("");
        tTanggal.setText("");
        tAlamat.setText("");
        tNama.setText("");
        cHotel.setSelectedIndex(0);
        tBayar.setText("");
        tKembali.setText("");
        }
        
        void aktif(){
        c1.setEnabled(true);
        c2.setEnabled(true);
        c3.setEnabled(true);
        tNama.setEnabled(true);
        tTanggal.setEnabled(true);
        tAlamat.setEnabled(true);
        tHarga.setEnabled(true);
        tBayar.setEnabled(true);
        tKembali.setEnabled(true);
        
        
        }
        
        void nonaktif(){
        c1.setEnabled(false);
        c2.setEnabled(false);
        c3.setEnabled(false);
        tNama.setEnabled(false);
        tTanggal.setEnabled(false);
        tAlamat.setEnabled(false);
        tHarga.setEnabled(false);
        tBayar.setEnabled(false);
        tKembali.setEnabled(false);
        }
        
        
        
        
       
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        c1 = new javax.swing.JCheckBox();
        c2 = new javax.swing.JCheckBox();
        c3 = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        tNama = new javax.swing.JTextField();
        tAlamat = new javax.swing.JTextField();
        tHarga = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cHotel = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        bIsi = new javax.swing.JButton();
        bTutup = new javax.swing.JButton();
        bBersih = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        tTanggal = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tBayar = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tKembali = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("NAMA");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 95, -1, -1));

        jLabel2.setText("ALAMAT");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        c1.setText("VVIP");
        c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c1ActionPerformed(evt);
            }
        });
        getContentPane().add(c1, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 283, -1, -1));

        c2.setText("VIP");
        c2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c2ActionPerformed(evt);
            }
        });
        getContentPane().add(c2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, -1, -1));

        c3.setText("STANDARD");
        c3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c3ActionPerformed(evt);
            }
        });
        getContentPane().add(c3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 283, -1, -1));

        jLabel3.setText("HARGA");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 335, -1, -1));
        getContentPane().add(tNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 151, 30));
        getContentPane().add(tAlamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 219, 30));
        getContentPane().add(tHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, 118, 30));

        jLabel5.setText("TIPE KAMAR");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        jLabel7.setText("HOTEL");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        cHotel.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        cHotel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-PILIH-", "ROYAL HOTEL", "MSC HOTEL", "VESA HOTEL" }));
        cHotel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cHotelActionPerformed(evt);
            }
        });
        getContentPane().add(cHotel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 125, 30));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 606, -1));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(606, 6, -1, -1));

        jPanel3.setBackground(new java.awt.Color(102, 0, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, -1, -1));

        jPanel4.setBackground(new java.awt.Color(0, 51, 51));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Bernard MT Condensed", 0, 18)); // NOI18N
        jLabel8.setText("PEMESANAN HOTEL");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, 31));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 60));

        jPanel5.setBackground(new java.awt.Color(0, 51, 51));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bIsi.setText("ISI DATA");
        bIsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bIsiActionPerformed(evt);
            }
        });
        jPanel5.add(bIsi, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, -1));

        bTutup.setText("TUTUP");
        bTutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTutupActionPerformed(evt);
            }
        });
        jPanel5.add(bTutup, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 77, -1));

        bBersih.setText("BERSIH");
        bBersih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBersihActionPerformed(evt);
            }
        });
        jPanel5.add(bBersih, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 78, -1));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 400, 50));

        jLabel6.setText("TANGGAL PEMESANAN");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));
        getContentPane().add(tTanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 150, 30));

        jLabel9.setText("BAYAR");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, -1, -1));

        tBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tBayarActionPerformed(evt);
            }
        });
        tBayar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tBayarKeyPressed(evt);
            }
        });
        getContentPane().add(tBayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, 120, 30));

        jLabel10.setText("KEMBALI");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, -1, -1));
        getContentPane().add(tKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 420, 120, 30));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cHotelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cHotelActionPerformed
       almt.setHotel(cHotel.getSelectedItem().toString());
       almt.pilih(almt.getHotel());
       tAlamat.setText(almt.getAlamat());        
    }//GEN-LAST:event_cHotelActionPerformed

    private void bIsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bIsiActionPerformed
       bersih();
       aktif();
    }//GEN-LAST:event_bIsiActionPerformed

    private void bBersihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBersihActionPerformed
        bersih();
    }//GEN-LAST:event_bBersihActionPerformed

    private void c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c1ActionPerformed
       c2.setSelected(false);
       c3.setSelected(false);
        if(c1.isSelected()==true){
            harga=2500000;    
        }
        else
            harga=0;
        tHarga.setText(Integer.toString(harga));
    }//GEN-LAST:event_c1ActionPerformed
        
    private void c2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c2ActionPerformed
        c1.setSelected(false);
        c3.setSelected(false);
        if(c2.isSelected()==true){
            harga=1700000;    
        }
        else
            harga=0;
        tHarga.setText(Integer.toString(harga));
    }//GEN-LAST:event_c2ActionPerformed

    private void c3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c3ActionPerformed
        c1.setSelected(false);
        c2.setSelected(false);
        if(c3.isSelected()==true){
            harga=1000000;    
        }
        else
            harga=0;
        tHarga.setText(Integer.toString(harga));
    }//GEN-LAST:event_c3ActionPerformed

    private void bTutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTutupActionPerformed
        int tutup;
        tutup=JOptionPane.showConfirmDialog(null, "Yakin Tutup Program?" ,"Konfirmasi",JOptionPane.YES_NO_OPTION);
        if(tutup==JOptionPane.YES_OPTION)
            dispose();
        else
            return;
    }//GEN-LAST:event_bTutupActionPerformed

    private void tBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tBayarActionPerformed
        
    }//GEN-LAST:event_tBayarActionPerformed

    private void tBayarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tBayarKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
           int a = Integer.parseInt(tHarga.getText());
           int b = Integer.parseInt(tBayar.getText());
           int c = b-a;
           tKembali.setText(Integer.toString(c));
        }
    }//GEN-LAST:event_tBayarKeyPressed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PemesananHotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PemesananHotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PemesananHotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PemesananHotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PemesananHotel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBersih;
    private javax.swing.JButton bIsi;
    private javax.swing.JButton bTutup;
    private javax.swing.JCheckBox c1;
    private javax.swing.JCheckBox c2;
    private javax.swing.JCheckBox c3;
    private javax.swing.JComboBox<String> cHotel;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField tAlamat;
    private javax.swing.JTextField tBayar;
    private javax.swing.JTextField tHarga;
    private javax.swing.JTextField tKembali;
    private javax.swing.JTextField tNama;
    private javax.swing.JTextField tTanggal;
    // End of variables declaration//GEN-END:variables
}

